Add install script on Windows
tonikasoft/fpsdk pull request #7
Opened 2020-04-13 21:20 UTC by dmitryrec

2020-04-16 20:12 UTC, ales-tsurko requested changes
Ты почти сделал это)

2020-04-16 20:12 UTC, ales-tsurko commented on install.win.bat
> +:: install.win.bat name destination_name plugin_path
Поменяй `plugin_path` на `plugins_dir`, а то получается, что это путь к плагину.

2020-04-16 20:12 UTC, ales-tsurko commented on install.win.bat
> +set PLUG_PATH=%3
Смотри, в моем случае в скрипте капсом были прописаны внутренние переменные, а строчными — аргументы. У тебя сейчас смешанно получается. Нужно либо все одинаково, либо чтобы какая-то логика была. Можешь их все сделать капсом, или все строчными, или которые из аргументов — строчными, а `DEFAULT_PATH` прописными (или наоборот), но если смешиваешь, это сбивает с толку.

2020-04-16 20:12 UTC, ales-tsurko commented on install.win.bat
> +    rd %PLUG_PATH%\Effects\%dest_name%
Папку нужно удалять рекурсивно. Хз, что мы там в будущем еще будем устанавливать. Посмотри [здесь](https://stackoverflow.com/a/97896/4429188), как это делается.

2020-04-16 20:12 UTC, AlesTsurko commented on install.win.bat
> +    move target\release\examples\%name%.dll %DEFAULT_PATH%\Effects\%dest_name%\%dest_name%_x64.dll
Чтобы убрать дублирование целого блока (DRY), лучше в проверке по аргументам переписывать какую-то конечную переменную. Например, если ты будешь переназначать `DEFAULT_PATH`, то тебе всего лишь нужно будет добавить блок для проверки 3-х аргументов и назначать в эту переменную значение из аргумента. А сам блок вообще вынести из `if`.

То есть примерно (не знаю про batch скрипты, проверь синтаксис):

```batch
if %argsCount%==3 (
    set DEFAULT_PATH=%3
)

rd %DEFAULT_PATH%\Effects\%dest_name%
md %DEFAULT_PATH%\Effects\%dest_name%
 
move target\release\examples\%name%.dll %DEFAULT_PATH%\Effects\%dest_name%\%dest_name%_x64.dll
```

И тогда можешь `DEFAULT_PATH` переименовать в `PLUG_PATH`, а бывший `PLUG_PATH` вообще убрать.

2020-04-16 20:12 UTC, AlesTsurko commented on install.win.bat
> +if %argsCount%==1 (
Во-первых, что если аргументов будет больше, чем нужно? Лучше проверить по "меньше двух или больше 3-х".

Во-вторых, такого рода валидацию лучше делать как можно раньше (ранний отказ), чтобы не тратилось время на все остальное... Тут, правда, не те масштабы) Но это в целом полезная привычка.

И не забудь здесь тоже изменить `plugin_path` на `plugins_dir`. Еще лучше `[plugins_dir]`, чтобы было понятно, что это необязательный аргумент.

2020-04-16 20:29 UTC, AlesTsurko commented on install.win.bat
> +set argsCount=0
Чуть не пропустил. Если уже используешь snake case, то `args_count`.

2020-04-17 11:33 UTC, dmitryrec commented on install.win.bat
> +if %argsCount%==1 (
это про проверку if %argsCount%==1 ?

2020-04-17 14:51 UTC, ales-tsurko requested changes

2020-04-17 14:51 UTC, AlesTsurko commented on install.win.bat
> +:: install.win.bat name destination_name plugin_path
Так ты ж не поменял)

Я говорил про коммент, это же висит к конкретной строке. Переменную, как-раз, можно было и не менять)

Еще просил показать, что это необязательный параметр, добавив его в квадратные скобки. То есть `[plugins_dir]`.

2020-04-17 14:51 UTC, AlesTsurko commented on install.win.bat
> +    move target\release\examples\%name%.dll %plugins_dir%\Effects\%dest_name%\%dest_name%_x64.dll
Удаление директория, если он уже существует, решил вообще убрать, вместо того, чтобы сделать рекурсивным?)

Еще обрати внимание, у тебя тут табуляция (отступы) ненужная.

2020-04-17 14:51 UTC, AlesTsurko commented on install.win.bat
> +    echo "Usage: install.win.bat name destination_name plugin_path"
Здесь тоже самое про **plugins_dir**.

2020-04-17 15:49 UTC, ales-tsurko approved these changes
🎆

2020-04-17 15:51 UTC, merged